import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { PageHeader } from '../../ui/PageHeader';
import { Card } from '../../ui/Card';
import styles from '../members/MembersPage.module.css';
const mockAssessments = [
    { id: 1, member: '김지영', date: '2024-12-10', instructor: '박강사', type: '초기 평가', status: 'completed' },
    { id: 2, member: '이수민', date: '2024-12-11', instructor: '박강사', type: '정기 평가', status: 'completed' },
    { id: 3, member: '박현우', date: '2024-12-12', instructor: '박강사', type: '초기 평가', status: 'scheduled' },
    { id: 4, member: '최민지', date: '2024-12-15', instructor: '박강사', type: '재평가', status: 'scheduled' },
    { id: 5, member: '정다은', date: '2024-12-08', instructor: '박강사', type: '정기 평가', status: 'completed' },
];
export function AssessmentsPage() {
    return (_jsxs("div", { className: styles.container, children: [_jsx(PageHeader, { title: "\uC2E0\uCCB4\uD3C9\uAC00", description: "\uD68C\uC6D0 \uC2E0\uCCB4\uD3C9\uAC00 \uAE30\uB85D\uC744 \uAD00\uB9AC\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4", action: {
                    label: '평가 등록',
                    onClick: () => console.log('평가 등록'),
                } }), _jsxs("div", { className: styles.toolbar, children: [_jsxs("div", { className: styles.searchBox, children: [_jsxs("svg", { viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", children: [_jsx("circle", { cx: "11", cy: "11", r: "8" }), _jsx("line", { x1: "21", y1: "21", x2: "16.65", y2: "16.65" })] }), _jsx("input", { type: "text", placeholder: "\uD68C\uC6D0\uBA85\uC73C\uB85C \uAC80\uC0C9" })] }), _jsxs("div", { className: styles.filters, children: [_jsxs("select", { className: styles.select, children: [_jsx("option", { value: "", children: "\uC804\uCCB4 \uC0C1\uD0DC" }), _jsx("option", { value: "completed", children: "\uC644\uB8CC" }), _jsx("option", { value: "scheduled", children: "\uC608\uC815" })] }), _jsxs("select", { className: styles.select, children: [_jsx("option", { value: "", children: "\uC804\uCCB4 \uC720\uD615" }), _jsx("option", { value: "initial", children: "\uCD08\uAE30 \uD3C9\uAC00" }), _jsx("option", { value: "regular", children: "\uC815\uAE30 \uD3C9\uAC00" }), _jsx("option", { value: "re", children: "\uC7AC\uD3C9\uAC00" })] })] })] }), _jsx(Card, { children: _jsxs("table", { className: styles.table, children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "\uD68C\uC6D0" }), _jsx("th", { children: "\uB0A0\uC9DC" }), _jsx("th", { children: "\uD3C9\uAC00 \uC720\uD615" }), _jsx("th", { children: "\uB2F4\uB2F9 \uAC15\uC0AC" }), _jsx("th", { children: "\uC0C1\uD0DC" }), _jsx("th", {})] }) }), _jsx("tbody", { children: mockAssessments.map((item, idx) => (_jsxs("tr", { style: { animationDelay: `${idx * 50}ms` }, children: [_jsx("td", { children: _jsxs("div", { className: styles.memberName, children: [_jsx("div", { className: styles.avatar, children: item.member.charAt(0) }), _jsx("span", { children: item.member })] }) }), _jsx("td", { className: styles.date, children: item.date }), _jsx("td", { children: item.type }), _jsx("td", { children: item.instructor }), _jsx("td", { children: _jsx("span", { className: `${styles.status} ${item.status === 'completed' ? styles.active : styles.hold}`, children: item.status === 'completed' ? '완료' : '예정' }) }), _jsx("td", { children: _jsx("button", { className: styles.actionBtn, children: _jsxs("svg", { viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", children: [_jsx("circle", { cx: "12", cy: "12", r: "1" }), _jsx("circle", { cx: "19", cy: "12", r: "1" }), _jsx("circle", { cx: "5", cy: "12", r: "1" })] }) }) })] }, item.id))) })] }) })] }));
}
