import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { PageHeader } from '../../ui/PageHeader';
import { Card } from '../../ui/Card';
import styles from './MembersPage.module.css';
const mockMembers = [
    { id: 1, name: '김지영', email: 'jiyoung@email.com', phone: '010-1234-5678', status: 'active', membership: '6개월 무제한', joinDate: '2024-01-15' },
    { id: 2, name: '이수민', email: 'sumin@email.com', phone: '010-2345-6789', status: 'active', membership: '3개월 주2회', joinDate: '2024-02-20' },
    { id: 3, name: '박현우', email: 'hyunwoo@email.com', phone: '010-3456-7890', status: 'inactive', membership: '1개월 체험', joinDate: '2024-03-10' },
    { id: 4, name: '최민지', email: 'minji@email.com', phone: '010-4567-8901', status: 'active', membership: '12개월 무제한', joinDate: '2023-12-01' },
    { id: 5, name: '정다은', email: 'daeun@email.com', phone: '010-5678-9012', status: 'hold', membership: '6개월 주3회', joinDate: '2024-01-28' },
];
export function MembersPage() {
    return (_jsxs("div", { className: styles.container, children: [_jsx(PageHeader, { title: "\uD68C\uC6D0", description: "\uD68C\uC6D0 \uC815\uBCF4\uB97C \uAD00\uB9AC\uD558\uACE0 \uAC80\uC0C9\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4", action: {
                    label: '회원 등록',
                    onClick: () => console.log('회원 등록'),
                } }), _jsxs("div", { className: styles.toolbar, children: [_jsxs("div", { className: styles.searchBox, children: [_jsxs("svg", { viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", children: [_jsx("circle", { cx: "11", cy: "11", r: "8" }), _jsx("line", { x1: "21", y1: "21", x2: "16.65", y2: "16.65" })] }), _jsx("input", { type: "text", placeholder: "\uC774\uB984, \uC774\uBA54\uC77C, \uC5F0\uB77D\uCC98\uB85C \uAC80\uC0C9" })] }), _jsxs("div", { className: styles.filters, children: [_jsxs("select", { className: styles.select, children: [_jsx("option", { value: "", children: "\uC804\uCCB4 \uC0C1\uD0DC" }), _jsx("option", { value: "active", children: "\uD65C\uC131" }), _jsx("option", { value: "inactive", children: "\uBE44\uD65C\uC131" }), _jsx("option", { value: "hold", children: "\uD640\uB529" })] }), _jsxs("select", { className: styles.select, children: [_jsx("option", { value: "", children: "\uC804\uCCB4 \uD68C\uC6D0\uAD8C" }), _jsx("option", { value: "unlimited", children: "\uBB34\uC81C\uD55C" }), _jsx("option", { value: "count", children: "\uD69F\uC218\uC81C" })] })] })] }), _jsx(Card, { children: _jsxs("table", { className: styles.table, children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "\uC774\uB984" }), _jsx("th", { children: "\uC5F0\uB77D\uCC98" }), _jsx("th", { children: "\uC774\uBA54\uC77C" }), _jsx("th", { children: "\uD68C\uC6D0\uAD8C" }), _jsx("th", { children: "\uC0C1\uD0DC" }), _jsx("th", { children: "\uAC00\uC785\uC77C" }), _jsx("th", {})] }) }), _jsx("tbody", { children: mockMembers.map((member, idx) => (_jsxs("tr", { style: { animationDelay: `${idx * 50}ms` }, children: [_jsx("td", { children: _jsxs("div", { className: styles.memberName, children: [_jsx("div", { className: styles.avatar, children: member.name.charAt(0) }), _jsx("span", { children: member.name })] }) }), _jsx("td", { children: member.phone }), _jsx("td", { className: styles.email, children: member.email }), _jsx("td", { children: member.membership }), _jsx("td", { children: _jsxs("span", { className: `${styles.status} ${styles[member.status]}`, children: [member.status === 'active' && '활성', member.status === 'inactive' && '비활성', member.status === 'hold' && '홀딩'] }) }), _jsx("td", { className: styles.date, children: member.joinDate }), _jsx("td", { children: _jsx("button", { className: styles.actionBtn, children: _jsxs("svg", { viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", children: [_jsx("circle", { cx: "12", cy: "12", r: "1" }), _jsx("circle", { cx: "19", cy: "12", r: "1" }), _jsx("circle", { cx: "5", cy: "12", r: "1" })] }) }) })] }, member.id))) })] }) })] }));
}
